mqtt:
  username: "mqttbroker"
  password: "Q8BssZ8WT#d67PWoqrHVe"
  host: "192.168.142.3"
  port: 1883
  topic: "frigate/events"
  alert_topic: "frigate_notify/object_detected"
pushover:
  api_key: "a1dw2su7dmwwpq1g1rp2iruz7hxwut"
  user_key: "uixuyk7ji1abkxunjgx7241awutdnr"
healthchecks:
  uuid: "5313a8a1-e394-44b3-bacc-ad0872ee54a6"
frigate_server:
  host: "https://frigate.wrightfamily.org"
web_server:
  url: "https://videoevents.wrightfamily.org"
log_info:
  level: "INFO"
  log_file: "frigatenotify.log"
  log_to_screen: true
cooldown_period: 60
