apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-notify-config
  labels:
    app: frigate-notify
data:
  config.yaml: |
    # MQTT Configuration
    # Note: Credentials are loaded from Kubernetes Secret via environment variables
    mqtt:
      username: "will-be-overridden-by-env"
      password: "will-be-overridden-by-env"
      host: "mqtt.txsww.com"
      port: 1883
      topic: "frigate/events"
      alert_topic: "frigate_notify/object_detected"

    # Pushover Configuration
    # Note: Credentials are loaded from Kubernetes Secret via environment variables
    pushover:
      api_key: "will-be-overridden-by-env"
      user_key: "will-be-overridden-by-env"

    # Healthchecks.io Configuration
    healthchecks:
      uuid: "will-be-overridden-by-env"

    # Frigate Server Configuration
    frigate_server:
      host: "will-be-overridden-by-env"

    # Web Server Configuration
    web_server:
      url: "https://frigate-notify.txsww.com"

    # Logging Configuration
    log_info:
      level: "INFO"
      log_file: "/app/logs/frigatenotify.log"
      log_to_screen: true

    # Camera Configuration - UPDATE THIS FOR YOUR CAMERAS
    cameras:
      - Garage
      - Back
      - Front
      - Driveway

    # Cooldown period between notifications (seconds)
    cooldown_period: 60

    # Database location
    database: /data/silence_settings.db

    # Door Settings - UPDATE THIS FOR YOUR DOORS
    door_settings:
      silence_period: 2          # Minutes to silence camera when door opens
      no_detection_timeout: 2     # Minutes - don't silence if recent detection
      doors:
        - topic: alarm/sensor/zone_11/state
          door: "Garage Interior Door"
          camera: Garage
        - topic: alarm/sensor/zone_10/state
          door: "Front Door"
          camera: Front
        - topic: alarm/sensor/zone_12/state
          door: "Back Door"
          camera: Back
