name: Release and Tag

on:
  push:
    branches:
      - master  # Changed from 'main' to match repository default branch

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      changelog: ${{ steps.tag_version.outputs.changelog }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for changelog generation

      - name: Bump version and create tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          initial_version: 2.0.0
          release_branches: master
          pre_release_branches: develop,beta
          tag_prefix: v
          # Commit message prefixes for version bumping:
          # feat: or feature: -> minor version bump
          # fix: or bugfix: -> patch version bump
          # BREAKING CHANGE: -> major version bump

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Output new version
        run: |
          echo "New version created: ${{ steps.tag_version.outputs.new_tag }}"
          echo "Changelog:"
          echo "${{ steps.tag_version.outputs.changelog }}"

  docker-build:
    name: Build and Push Docker Image
    needs: release
    if: ${{ needs.release.outputs.new_tag }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.release.outputs.new_tag }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},value=${{ needs.release.outputs.new_tag }}
            type=semver,pattern={{major}}.{{minor}},value=${{ needs.release.outputs.new_tag }}
            type=semver,pattern={{major}},value=${{ needs.release.outputs.new_tag }}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output image tags
        run: |
          echo "Docker image built and pushed with tags:"
          echo "${{ steps.meta.outputs.tags }}"
